### ISSUE TITLE
New Digital Ocean IPs?

### ISSUE THREAD

**Issue by caxanga334** [Maikuolan/zbb-badip-fork#2]
I got two hits from a robot on my website. One of them was blocked by Digital Ocean blocks. The other one wasn't, I did a look up on his IP and found that his IP is also from Digital Ocean.
http://bgp.he.net/AS62567

**Comment by Maikuolan** [comment]
Comparing them just now, I can't seem to find any differences between the ranges currently listed in the codebase and the ranges currently announced by their ASNs.

What was the IP address that wasn't blocked?

**Comment by caxanga334** [comment]
104.131.220.136
I am also attaching my killed_log.txt
[killed_log_upload.txt](https://github.com/Maikuolan/zbb-badip-fork/files/128128/killed_log_upload.txt)

**Comment by Maikuolan** [comment]
Ah, okay. I've figured out what's happened. :-)

I released an update 7 days ago ("`BADIP-2016-02+U.1`") because we found a new ASN for Digital Ocean, and so, I had to update all their ranges here (there were a few changes with the old ASNs, too); The version you're using ("`BADIP-2016-01+U.12`") doesn't contain the new ranges, but the latest version should.

I've been releasing some of these updates in rather tight intervals, so, it's easy to miss them. If you update to the latest version, though, the problem should be resolved.

**Comment by caxanga334** [comment]
I did updated when I saw this but I didn't found the CIDR ranges listed on the AS62567 in the signatures. I blocked the CIDR rages and I will have to wait until any bot from Digical Ocean hit my website to see if it was blocked by two signatures.

**Comment by Maikuolan** [comment]
Okay.

**Comment by Maikuolan** [comment]
16 days have passed, so, I'll marked this issue as closed for now. If the problem reappears, though, feel free to reopen the issue. :-)
