### ISSUE TITLE
sorry for the pull requests..

### ISSUE THREAD

**Issue by MixingOnBeat** [Maikuolan/zbb-badip-fork#5]
Sorry, learning how to merge / update my fork from your repo (original).

I am used to BitBucket, but new to GitHub.

I think I finally got the hang of it. (I think?) :-)

**Comment by Maikuolan** [comment]
No worries; It's not a problem. GitHub can definitely take a while to get familiar with due to how different it is from other commonly used systems, but once you get the hang of it, there's definitely benefits to be felt from using it. :-)

This is an article I've used as a point of reference on more than one occasion in the past when making pull requests; Definitely helps as a reminder of what's what and how it all works:

https://help.github.com/articles/using-pull-requests/

Especially this bit (because confusing the *"head branch"* and the *"base branch"*, I think, is probably the number one most common mistake made when making pull requests; I've made this specific mistake a few times before):

> The easiest way of thinking about the branch range is this: the *base branch* is __where__ you think changes should be applied, the *head branch* is __what__ you would like to be applied.
> 
> When you change the base repository, you also change notifications for the pull request. Everyone that can push to the base repository will receive an email notification and see the new pull request in their dashboard the next time they sign in.
> 
> When you change any of the info in the branch range, the commit and files changed preview areas will update to show your new range.

**Comment by MixingOnBeat** [comment]
Thanks.  I ended up creating a YouTube tutorial on how to do the process.  Plus a reminder for myself whenever I need to do it. http://www.mixingonbeat.com/phpbb/viewtopic.php?f=169&t=9589

**Comment by Maikuolan** [comment]
Tutorial looks good. :+1:
